### PR TITLE
Particles

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by democat3457** [comment]
Can't figure out how to not have a merge conflict.

**Comment by prestja** [comment]
I can fix the merge conflicts no problem. Can you drop me a sample .cfg to test these particles with?

**Comment by democat3457** [comment]
:shrug: it's supposed to have backwards compatability with the existing 1.7.3 particle system, but since most packs will have already omitted particles, it's fairly redundant. Configs from 1.7.3 packs should work, but I don't have any on hand.

**Comment by R-T-B** [comment]
I also lack a testing example.  If we can get that, I think we can get this merged pretty quickly.  Sorry but hunting down old links isn't really what I should be doing with my limited time to work on Kopernicus, so any help you can offer there is vastly appreciated.

Oh, and it goes without saying, thanks for writing this in the firstplace, of course.  We don't mean to seem ungrateful, we are just stretched thin.

**Comment by R-T-B** [comment]
Your pull request is presently in bleeding edge testing with a select group of testing users from the forums.  I'll let you know the results.

It's been merged to my "bleeding edge" branch for this purpose:

https://github.com/R-T-B/Kopernicus/tree/ParticleLand

**Comment by R-T-B** [comment]
In short, no issues reported with particles yet.  I have specifically asked testers to seek out old planet packs that rely on particles in the next testing batch.  If all goes well, I believe we will integrate your pull request with a target for 1.10 release, no bugs withstanding.  Thank you very much for your work on this.

**Comment by democat3457** [comment]
No problem! After this PR gets merged, I may work on what Thomas was mentioning over on the original PR, with a complete Particles revamp...

**Comment by R-T-B** [comment]
We are getting reports of GPP (Galileos planet pack) crashing Kopernicus via something about particles in my 1.10 testing branch.  Relevant logs from a player follow:

https://www.dropbox.com/sh/nce4nd4tu60y6go/AAAMMLfLpyCVsfK3GQi92VRqa?dl=0
https://www.dropbox.com/sh/nce4nd4tu60y6go/AAAMMLfLpyCVsfK3GQi92VRqa?dl=0&preview=Lili.Body.log

The exact tree being used for this report can be found here:

https://github.com/R-T-B/Kopernicus/tree/dev110

(Intended for 1.10.0)

**Comment by democat3457** [comment]
KSP.log?

**Comment by R-T-B** [comment]
oops, will ask him for that, standby.

EDIT:  Got it, be warned, it's big:

https://www.dropbox.com/s/l6n5i87pmu78xyh/KSP.log?dl=0

**Comment by R-T-B** [comment]
Any idea what's going on here?  The particle code has otherwise apparently performed well.  It's seemingly just GPP.

**Comment by democat3457** [comment]
Tbh, the logs aren't very descriptive, but with a first glance at the mod configs, ~~it could be that the particles have no target.~~
EDIT: nevermind, it's actually set by default as "None" in the code.

**Comment by R-T-B** [comment]
Yeah, it's weird.  I could try doing a special debug build for the affected user rather than release-config and see if that helps.

Would that be good?  It should turn on tracing variable and some other stuff, and maybe give us some more output.

**Comment by democat3457** [comment]
Sure, give it a try. Could also be that some options are missing, like the `mesh`.

**Comment by R-T-B** [comment]
I think a debug build is a good starting point.  I will produce one and ask the affected user to run it tomorrow.

**Comment by StollD** [comment]
To actually get more information on the stacktraces you don't just need a debug build of Kopernicus, you need a debug build of [KSP](https://forum.kerbalspaceprogram.com/index.php?/topic/102909--).

However there is enough information already available to figure out the issue (at least for me *whistles*):

In the `Lili.Body.log` that is linked above you find this stacktrace:
```
[LOG 17:30:06]: Inner Exception Was Recorded: Object reference not set to an instance of an object
  at Kopernicus.Configuration.ParticleLoader..ctor () [0x00034] in <694859e4aecc400d872b35366335e644>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
```
This tells us that a nullreference exception occured in the [constructor for the ParticleLoader](https://github.com/democat3457/Kopernicus/blob/9551042e6ccf104efa4c8ec052ad8c3870c34a9d/src/Kopernicus/Configuration/ParticleLoader.cs#L292-L300). There are three possible causes for a NRE here:
* `generatedBody` is null. Unlikely because then everything would break, not just the particle loader.
* `Value` is null
* `Value.emitter` is null

In the two latter cases the issue would come from the [Create method in PlanetParticleEmitter](https://github.com/democat3457/Kopernicus/blob/9551042e6ccf104efa4c8ec052ad8c3870c34a9d/src/Kopernicus/Components/PlanetaryParticle.cs#L59). When looking at that method, you might notice that the `emitter` field is never assigned. There is a local variable thats called emitter, but the `PlanetParticleEmitter` object is returned immideately after creating it, without assigning anything to its emitter field.

The *actual* `KSPParticleEmitter` object is created and assigned later, in [Awake()](https://github.com/democat3457/Kopernicus/blob/9551042e6ccf104efa4c8ec052ad8c3870c34a9d/src/Kopernicus/Components/PlanetaryParticle.cs#L79). But Awake() won't run until the next frame, at which point Kopernicus loader will already have completed its work and KSP will start spawning the solar system.

**Comment by democat3457** [comment]
Thanks! Would setting the `emitter` of the returned result in the Create method to `gameObject.AddComponent<KSPParticleEmitter>()` work, or would `gameObject` be `null` in the constructor?

**Comment by R-T-B** [comment]
> 
> 
> To actually get more information on the stacktraces you don't just need a debug build of Kopernicus, you need a debug build of [KSP](https://forum.kerbalspaceprogram.com/index.php?/topic/102909--).
> 
> However there is enough information already available to figure out the issue (at least for me _whistles_):
> 
> In the `Lili.Body.log` that is linked above you find this stacktrace:
> 
> ```
> [LOG 17:30:06]: Inner Exception Was Recorded: Object reference not set to an instance of an object
>   at Kopernicus.Configuration.ParticleLoader..ctor () [0x00034] in <694859e4aecc400d872b35366335e644>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
> ```
> 
> This tells us that a nullreference exception occured in the [constructor for the ParticleLoader](https://github.com/democat3457/Kopernicus/blob/9551042e6ccf104efa4c8ec052ad8c3870c34a9d/src/Kopernicus/Configuration/ParticleLoader.cs#L292-L300). There are three possible causes for a NRE here:
> 
>     * `generatedBody` is null. Unlikely because then everything would break, not just the particle loader.
> 
>     * `Value` is null
> 
>     * `Value.emitter` is null
> 
> 
> In the two latter cases the issue would come from the [Create method in PlanetParticleEmitter](https://github.com/democat3457/Kopernicus/blob/9551042e6ccf104efa4c8ec052ad8c3870c34a9d/src/Kopernicus/Components/PlanetaryParticle.cs#L59). When looking at that method, you might notice that the `emitter` field is never assigned. There is a local variable thats called emitter, but the `PlanetParticleEmitter` object is returned immideately after creating it, without assigning anything to its emitter field.
> 
> The _actual_ `KSPParticleEmitter` object is created and assigned later, in [Awake()](https://github.com/democat3457/Kopernicus/blob/9551042e6ccf104efa4c8ec052ad8c3870c34a9d/src/Kopernicus/Components/PlanetaryParticle.cs#L79). But Awake() won't run until the next frame, at which point Kopernicus loader will already have completed its work and KSP will start spawning the solar system.

Ah, that makes sense.

I'm still glad we have your Kopernicus-genius to weigh on from time to time.  Between this and work, I'd probably have honestly ripped out the particle system in next 1.10 release before getting time to properly figure this out.  Thank you.



> 
> 
> Thanks! Would setting the `emitter` of the returned result in the Create method to `gameObject.AddComponent<KSPParticleEmitter>()` work, or would `gameObject` be `null` in the constructor?

I'll run some tests and find out today...  heh.

**Comment by StollD** [comment]
> Thanks! Would setting the `emitter` of the returned result in the Create method to `gameObject.AddComponent<KSPParticleEmitter>()` work, or would `gameObject` be `null` in the constructor?

Yes that would work. Remember, you are adding the component to the GameObject, so it has to exist for the AddComponent to work. ;) Even if the gameObject property was null, you could just use the GameObject variable you declared yourself (emitter).

**Comment by democat3457** [comment]
This should work?

**Comment by R-T-B** [comment]
I'll have your change pushed out to my testers by tomorrow.  Just getting slammed with work here right now, sorry for the slow replies/testing.

**Comment by democat3457** [comment]
:+1: Sounds good, no rush!

**Comment by R-T-B** [comment]
I got the build built and distributed today.  Now we're just waiting for results.  It loaded for me, at least. :)

**Comment by R-T-B** [comment]
I'm going to close this old pull request if it's all the same to you.  Your Particles have been performing great in the few people that use them, and I hope we can start encouraging planet pack authors to proceed with reimplementing some fun effects when it hits stock with my 1.10.1 branch merging into here (this should happen around the CKANing of 1.9.1).

You of course were the author and in 1.10.1, the commit that adds particles on my branch actually sources this PR and credits you directly.  We really appreciate your hard work on this, as I would've just assumed this "too hard / not worth it" vs the other bugs.  Consider this "closed, but accepted," at least from me.

**Comment by democat3457** [comment]
Yay! Would this change also be reflected upon a future 1.8 version as well, since 1.8 has no particle support as of yet?

**Pull request closed without merging**
