### PR TITLE
Remove the log spam from scatter colliders

### PR DESCRIPTION
**Pull request by StollD**
I still had this lying around on my disk, so it should probably be applied instead of thrown away. It is pretty much untested but it should work.

### CODE REVIEW

**Review by R-T-B — COMMENTED** [review]
I'm not up to date on this.  Does the scatter collider system no longer function?  If so, I don't feel it's our responsibility to fix it as our aim is at most, feature parity of the 1.8 release, and thus I approve of this.   Just my 2 cents.

**Comment by StollD** [comment]
The scatter collider system does function (You might notice I didn't remove the code that actually adds colliders), but it is needlessly complicated. There is no need to constantly flood the log with "12345 colliders added" when someone flies over the surface and constantly generates new scatters. Especially since doing any form of (repeated) IO means death to performance.

It's also not neccessary to explicitly remove colliders, since that is already done by the `ModularScatter` component, by removing the entire object when it is not needed anymore (well, not now, but after reverting these 3 commits).

**Comment by R-T-B** [comment]
Can you make this same pull request against my branch?  https://github.com/R-T-B/Kopernicus

It'll just be easier for me to automerge for testing that way.  I tend to test bleeding edge stuff in my own builds there in my personal branch.  Once playtested, I'm actually eager to merge this, and will sign off happily.  Scatters have performed badly for a while and I/O could indeed be part of the cause.

**Comment by StollD** [comment]
The changes are contained to a single file, so you could just download that and overwrite your local one with it. I feel like that might be faster. But if you want I can make a second PR later.

**Comment by R-T-B** [comment]
Oh, if it's a single file change I'll deal with it tomorrow.  Sorry, it's late, I've been working hard and things start to bleed together in my mind... lol.

**Comment by R-T-B** [comment]
This has been merged into my pull request above, and looks good to me.

**Review by R-T-B — APPROVED** [review]

**Comment by R-T-B** [comment]
I would advise merging this.  It worked in my test environment and did seem to improve performance of scatters.

**Pull request merged**
