### PR TITLE
Russian localization

### PR DESCRIPTION
**Pull request by ra4nd0m**

### CODE REVIEW

**Comment by R-T-B** [comment]
Oh, thank you.  I'll try to see to it this goes into next release, pending a brief verification (not saying it's not correct I just know someone who can read cyrillic/speak russian so I think it would not hurt to double check).

**Comment by ra4nd0m** [comment]
Excellent! Please be worry that the line: "Use absolute/relative exposure" was too long in russian so i had to shorten it to fit it into the window

**Comment by R-T-B** [comment]
This passed my uncle's inspection, and he used to write manuals for a living so I think he'd know.  I'm going to approve it for next release.

**Comment by R-T-B** [comment]
We have some minor corrections from native speakers that will be going in next.  But overall the feedback has been good.

**Comment by ra4nd0m** [comment]
Well, this is really good. I'm happy that you instead of many other modders actually care to check translation. Usually when I make a localization nobody cares to check how correct it is.

**Comment by R-T-B** [comment]
Thanks, I try.  We appreciate any translations really but it's generally good to check them for being at least a little correct, hehe.

**Pull request merged**
